openapi: 3.0.0
info:
  description: >-
    These are the endpoints provided by the Central Ledger server of CAPTOR.
    These endpoints are used by the Inspect and Transport applications. The
    Inspect application will use the endpoints with inspection tags and the
    Transport application will use the endpoints with trip tags
  version: 2.0.0
  title: Central Ledger
servers:
  - url: 'https://api.centralledger.com/v1'
tags:
  - name: trip
    description: Everything related with the transportation of a set of goods.
  - name: inspection
    description: Everything related with the inspection of transportation of goods.
paths:
  /trip:
    post:
      tags:
        - trip
      summary: Add a new trip
      description: >-
        This endpoint is used to report a scheduled transportation of a set of
        specific goods. It received the information about the transportation.
      operationId: addTrip
      security:
        - ledger_auth:
            - 'write:trips'
            - 'read:trips'
  '/trip/{tripId}':
    get:
      tags:
        - trip
      summary: Find trip by ID
      description: >-
        This endpoint is used to return information about a submitted scheduled
        transportation of a set of specific goods. It receives the ID of the
        specific trip and returns the trip information.
      operationId: getTripById
      security:
        - ledger_auth:
            - 'read:trips'
  '/trip/{tripId}/begin':
    post:
      tags:
        - trip
      summary: Initialize trip
      description: >-
        This endpoint is used to indicate the initialization of a scheduled
        transportion of a specific set of goods. It receives the ID of the
        specific trip and the initial coordinates of the trip.
      operationId: initializeTrip
      security:
        - ledger_auth:
            - 'write:trips'
            - 'read:trips'
  '/trip/{tripId}/locate':
    post:
      tags:
        - trip
      summary: Update trip location
      description: >-
        This endpoint is used to report the current location of the
        transportation. It receives the ID of the specific trip and the current
        coordinates of the trip.
      operationId: locateTrip
      security:
        - ledger_auth:
            - 'write:trips'
            - 'read:trips'
    get:
      tags:
        - trip
      summary: Get current trip location
      description: >-
        This endpoint is used to retrieve the current location of the
        transportation. It receives the ID of the specific trip and it returns
        the current coordinates of the trip.
      operationId: getTripLocation
      security:
        - ledger_auth:
            - 'read:trips'
  '/trip/{tripId}/end':
    post:
      tags:
        - trip
      summary: End trip
      description: >-
        This endpoint is used to report the end of the transportation. It
        receives the ID of the specific trip and the coordinates of the final
        location of the trip.
      operationId: endTrip
      security:
        - ledger_auth:
            - 'write:trips'
            - 'read:trips'
  '/trip/{tripId}/inspect':
    get:
      tags:
        - trip
      summary: Check if trip was selected for inspection
      description: >-
        This endpoint is used to check if the specific trip was selected for
        inspection. It received the ID of the trip and returns a boolean
        indicating if the trip was selected.
      operationId: checkTripInspection
      security:
        - ledger_auth:
            - 'read:trips'
  /inspect:
    post:
      tags:
        - inspection
      summary: Add a new checkpoint
      description: >-
        This endpoint is used to register a checkpoint. It receives the
        checkpoint details adn returns the ID of the checkpoint.
      operationId: addCheckpoint
      security:
        - ledger_auth:
            - 'write:inspections'
            - 'read:inspections'
  '/inspect/{checkpointId}':
    get:
      tags:
        - inspection
      summary: Show information about a checkpoint
      description: >-
        This endpoint is used to return the information regarding a specific
        checkpoint. It receives the ID of the checkpoint and returns the
        information about the checkpoint.
      operationId: showCheckpoint
      security:
        - ledger_auth:
            - 'read:inspections'
  '/inspect/{checkpointId}/select':
    post:
      tags:
        - inspection
      summary: Select a random vehicle for inspection
      description: >-
        This endpoint is used to select a trip for inspection. It receives the
        ID of the checkpoint and returns the ID of the inspection
      operationId: selectInspection
      security:
        - ledger_auth:
            - 'write:inspections'
            - 'read:inspections'
  '/inspect/{checkpointId}/update/{inspectionId}':
    get:
      tags:
        - inspection
      summary: Show a inspection proof
      description: >-
        This endpoint is used to show a inspection proof. It receives the ID of
        the checkpoint and the ID of the inspection and it returns the
        inspection info and proof.
      operationId: showInspection
      security:
        - ledger_auth:
            - 'read:inspections'
    post:
      tags:
        - inspection
      summary: Upload a inspection proof
      description: >-
        This endpoint is used to upload a inspection proof. It receives the ID
        of the checkpoint, the ID of the inspection and the inspection proof
      operationId: updateInspection
      security:
        - ledger_auth:
            - 'write:inspections'
            - 'read:inspections'
components:
  securitySchemes:
    ledger_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://centralledger.com'
          tokenUrl: 'https://centralledger.com'
          scopes:
            'write:trips': modify trips
            'read:trips': read your trips
            'write:inspections': modify inspections
            'read:inspections': read inspections
    api_key:
      type: apiKey
      name: api_key
      in: header